name: Flaky Tests
on: [push]

jobs:
  build:
    name: Running Flaky Tests
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v2
        with:
          repository: kacgomez/idoft
          ref: b31c29526ac35b32b03d8cf9017e79a51fbe43e8
          
        
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
          
      - run: ls
