name: Flaky Tests
on: [push]

jobs:
  build:
    name: Running Flaky Tests
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v2
        with:
          repository: TestingResearchIllinois/idoft
          ref: b31c29526ac35b32b03d8cf9017e79a51fbe43e8      
        
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
          
      - name: Get 10 random tests
        run: grep ,ID,, pr-data.csv | grep -v \\[ | shuf --random-source=<(while :; do echo kgomez22@gmu.edu; done) | head
      
      
      
 #     - name: Clone first test's repo
 #       run: git clone https://github.com/vojtechhabarta/typescript-generator
 #            
 #     - run: cd typescript-generator
 #    
 #     - name: Checkout the latest commit
 #       uses: actions/checkout@v2
 #       with:
 #         repository: vojtechhabarta/typescript-generator
 #         ref: c19d407fea52612e7b7cd20620059736aec9a6a9
 #         
 #     - name: Compile the module
 #       run: mvn test-compile -pl typescript-generator-core -am
 #       
 #     - name: A Passing Test
 #       run: mvn -pl typescript-generator-core test -Dtest=cz.habarta.typescript.generator.TaggedUnionsTest#testTaggedUnionsWithInterfaces
 #       
 #     - name: A failing test with NonDex tool
 #       run: mvn -pl typescript-generator-core edu.illinois:nondex-maven-plugin:1.1.2:nondex -Dtest=cz.habarta.typescript.generator.TaggedUnionsTest#testTaggedUnionsWithInterfaces -DnondexRuns=10
        
        

  job2:
    runs-on: ubuntu-latest
    steps:
      - name: Clone second test's repo
        run: git clone https://github.com/OpenHFT/Chronicle-Wire
             
      - run: cd Chronicle-Wire
     
      - name: Checkout the latest commit
        uses: actions/checkout@v2
        with:
          repository: OpenHFT/Chronicle-Wire
          ref: a0aa1a2cb628b7b8dbb541c149442776026012ef
          
      - name: Compile the module
        run: mvn test-compile -pl . -am
        
      - name: A Passing Test
        run: mvn -pl . test -Dtest=net.openhft.chronicle.wire.MicroLongConverterTest#testMicro
        
      - name: A failing test with NonDex tool
        run: mvn -pl . edu.illinois:nondex-maven-plugin:1.1.2:nondex -Dtest=net.openhft.chronicle.wire.MicroLongConverterTest#testMicro -DnondexRuns=10  

