name: Flaky Tests
on: [push]

jobs:
  build:
    name: Running Flaky Tests
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v2
        with:
          repository: kacgomez/idoft
          ref: b31c29526ac35b32b03d8cf9017e79a51fbe43e8      
        
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
          
      - name: Get 10 random tests
        run: grep ,ID,, pr-data.csv | grep -v \\[ | shuf --random-source=<(while :; do echo kgomez22@gmu.edu; done) | head
        
      - run: cd
      
      - name: Clone test's repo
        run: git clone https://github.com/vojtechhabarta/typescript-generator
        
      - run: cd typescript-generator
      - uses: actions/checkout@v2
        with:
          ref: caef58bfe55a8cd1fc5d7368c19e9ff818a7b7fa
        
      - run: ls
